development:
  APP_URL: 'http://localhost:3000/api/v1'
  CORS_DOMAINS: CORS_DOMAINS

staging:
  APP_URL: 'http://YOUR_HOST/api/v1'
  CORS_DOMAINS: CORS_DOMAINS

production:
  APP_URL: 'http://YOUR_HOST/api/v1'
  CORS_DOMAINS: CORS_DOMAINS